treemap-beta
    "HumanResources"
        "Department":1
        "Employee":1
        "EmployeeDepartmentHistory":1
        "EmployeePayHistory":1
        "JobCandidate":1
        "Shift":1
    "Person"
        "Address":1
        "AddressType":1
        "BusinessEntity":1
        "BusinessEntityAddress":1
        "BusinessEntityContact":1
        "ContactType":1
        "CountryRegion":1
        "EmailAddress":1
        "Password":1
        "Person":1
        "PersonPhone":1
        "StateProvince":1
    "Production"
        "BillOfMaterials":1
        "Culture":1
        "Location":1
        "Product":1
        "ProductCategory":1
        "ProductCostHistory":1
        "ProductDescription":1
        "ProductInventory":1
        "ProductSubcategory":1
        "TransactionHistory":1
        "UnitMeasure":1
        "WorkOrder":1
        "WorkOrderRouting":1
    "Purchasing"
        "ProductVendor":1
        "PurchaseOrderDetail":1
        "PurchaseOrderHeader":1
        "ShipMethod":1
        "Vendor":1
    "Sales "
        "CountryRegionCurrency":1
        "CreditCard":1
        "Currency":1
        "CurrencyRate":1
        "Customer":1
        "PersonCreditCard":1
        "SalesOrderDetail":1
        "SalesOrderHeader":1
        "SalesOrderHeaderSalesReason":1
        "SalesPerson":1
        "SalesTaxRate":1
        "SalesTerritory":1
        "SalesTerritoryHistory":1
        "ShoppingCartItem":1
        "SpecialOffer":1
        "SpecialOfferProduct":1
        "Store":1

