SELECT 
city.WWI_City_ID AS "City Code",
city.City AS "City Name",
city.State_Province AS "State/Province",
city.Country AS "Country",
city.Continent AS "Continent",
city.Sales_Territory AS "Sales Territory",
city.Region AS "Region",
city.Subregion AS "Subregion",
city.Latest_Recorded_Population AS "Latest Recorded Population",
customer.WWI_Customer_ID AS "Customer Code",
customer.Customer AS "Customer Name",
customer.Bill_To_Customer AS "Billing Customer Name",
customer.Category AS "Customer Category",
customer.Buying_Group AS "Buying Customer Group",
customer.Primary_Contact AS "Primary Contact",
customer.Postal_Code AS "Postal Code",
stockitem.WWI_Stock_Item_ID AS "Stock Item Code",
stockitem.Stock_Item AS "Stock Item Name",
stockitem.Color AS "Item Color",
stockitem.Selling_Package AS "Item Selling Package",
stockitem.Buying_Package AS "Item Buying Package",
stockitem.Brand AS "ItemBrand",
stockitem.Size As "Item Size",
stockitem.Lead_Time_Days AS "Item Lead Time (Days)",
stockitem.Quantity_Per_Outer AS "Item Quantity Per Outer",
stockitem.Is_Chiller_Stock AS "Is Chiller Item Stock",
stockitem.Barcode AS "Item Barcode",
stockitem.Tax_Rate AS "Item Tax Rate",
stockitem.Unit_Price AS "Item Unit Price",
stockitem.Recommended_Retail_Price AS "Item Recommended Retail Price",
stockitem.Typical_Weight_Per_Unit AS "Item Typical Weight Per Unit",
orderDate.ISO_Week_Number AS "Order ISO Week Number",
orderDate.Date AS "Order Date",
orderDate.Day_Number AS "Order Day Number",
orderDate.Day AS "Order Day",
orderDate.Month AS "Order Month",
orderDate.Short_Month AS "Order Short Month",
orderDate.Calendar_Month_Number AS "Order Calendar Month Number",
orderDate.Calendar_Month_Label AS "Order Calendar Month Label",
orderDate.Calendar_Year AS "Order Calendar Year",
orderDate.Calendar_Year_Label AS "Order Calendar Year Label",
orderDate.Fiscal_Month_Number AS "Order Fiscal Month Number",
orderDate.Fiscal_Month_Label AS "Order Fiscal Month Label",
orderDate.Fiscal_Year AS "Order Fiscal Year",
orderDate.Fiscal_Year_Label AS "Order Fiscal Year Label",
pickerDate.Date AS "Picker Date",
pickerDate.Day_Number AS "Picker Day Number",
pickerDate.Day AS "Picker Day",
pickerDate.Month AS "Picker Month",
pickerDate.Short_Month AS "Picker Short Month",
pickerDate.Calendar_Month_Number AS "Picker Calendar Month Number",
pickerDate.Calendar_Month_Label AS "Picker Calendar Month Label",
pickerDate.Calendar_Year AS "Picker Calendar Year",
pickerDate.Calendar_Year_Label AS "Picker Calendar Year Label",
pickerDate.Fiscal_Month_Number AS "Picker Fiscal Month Number",
pickerDate.Fiscal_Month_Label AS "Picker Fiscal Month Label",
pickerDate.Fiscal_Year AS "Picker Fiscal Year",
pickerDate.Fiscal_Year_Label AS "Picker Fiscal Year Label",
pickerDate.ISO_Week_Number AS "Picker ISO Week Number",
SalesPerson.WWI_Employee_ID AS "Sales Person Code",
SalesPerson.Employee AS "Sales Person Name",
SalesPerson.Preferred_Name AS "Sales Person Preferred Name",
SalesPerson.Is_Salesperson AS "Is Sales Person",
PickerPerson.WWI_Employee_ID AS "Picker Person Code",
PickerPerson.Employee AS "Picker Person Name",
PickerPerson.Preferred_Name AS "Picker Person Preferred Name",
PickerPerson.Is_Salesperson AS "Is Picker Person",
orders.WWI_Order_ID AS "Order Code",
orders.WWI_Backorder_ID AS "Order Backorder Code",
orders.Description AS "Order Description",
orders.Package AS "Order Package",
orders.Quantity AS "Order Quantity",
orders.Unit_Price AS "Order Unit Price",
orders.Tax_Rate AS "Order Tax Rate",
orders.Total_Excluding_Tax AS "Order Total Excluding Tax",
orders.Tax_Amount AS "Order Tax Amount",
orders.Total_Including_Tax AS "Order Total Including Tax"
FROM 
iceberg_scan('file:///C:/data/data_files/iceberg/WideWorldImportersDW/fact/order', ("version" = '?'), (allow_moved_paths = CAST('t' AS BOOLEAN))) AS orders LEFT OUTER JOIN
iceberg_scan('file:///C:/data/data_files/iceberg/WideWorldImportersDW/Dimension/City', ("version" = '?'), (allow_moved_paths = CAST('t' AS BOOLEAN)))  AS city ON orders.City_Key = city.City_Key LEFT OUTER JOIN
iceberg_scan('file:///C:/data/data_files/iceberg/WideWorldImportersDW/Dimension/Customer', ("version" = '?'), (allow_moved_paths = CAST('t' AS BOOLEAN)))  AS customer ON orders.Customer_Key = customer.Customer_Key LEFT OUTER JOIN
iceberg_scan('file:///C:/data/data_files/iceberg/WideWorldImportersDW/Dimension/Stock_Item', ("version" = '?'), (allow_moved_paths = CAST('t' AS BOOLEAN)))  AS stockitem ON orders.Stock_Item_Key = stockitem.Stock_Item_Key LEFT OUTER JOIN
iceberg_scan('file:///C:/data/data_files/iceberg/WideWorldImportersDW/Dimension/Date', ("version" = '?'), (allow_moved_paths = CAST('t' AS BOOLEAN))) AS orderDate ON orders.Order_Date_Key = orderDate.Date LEFT OUTER JOIN
iceberg_scan('file:///C:/data/data_files/iceberg/WideWorldImportersDW/Dimension/Date', ("version" = '?'), (allow_moved_paths = CAST('t' AS BOOLEAN))) AS pickerDate ON orders.Picked_Date_Key = pickerDate.Date LEFT OUTER JOIN
iceberg_scan('file:///C:/data/data_files/iceberg/WideWorldImportersDW/Dimension/Employee', ("version" = '?'), (allow_moved_paths = CAST('t' AS BOOLEAN)))  AS SalesPerson ON orders.Salesperson_Key = SalesPerson.Employee_Key LEFT OUTER JOIN
iceberg_scan('file:///C:/data/data_files/iceberg/WideWorldImportersDW/Dimension/Employee', ("version" = '?'), (allow_moved_paths = CAST('t' AS BOOLEAN)))  AS PickerPerson ON orders.Salesperson_Key = PickerPerson.Employee_Key AND orders.Picker_Key = PickerPerson.Employee_Key

/*
SELECT 
city.WWI_City_ID AS `City Code`,
city.City AS `City Name`,
city.State_Province AS `State/Province`,
city.Country AS `Country`,
city.Continent AS `Continent`,
city.Sales_Territory AS `Sales Territory`,
city.Region AS `Region`,
city.Subregion AS `Subregion`,
city.Latest_Recorded_Population AS `Latest Recorded Population`,
customer.WWI_Customer_ID AS `Customer Code`,
customer.Customer AS `Customer Name`,
customer.Bill_To_Customer AS `Billing Customer Name`,
customer.Category AS `Customer Category`,
customer.Buying_Group AS `Buying Customer Group`,
customer.Primary_Contact AS `Primary Contact`,
customer.Postal_Code AS `Postal Code`,
stockitem.WWI_Stock_Item_ID AS `Stock Item Code`,
stockitem.Stock_Item AS `Stock Item Name`,
stockitem.Color AS `Item Color`,
stockitem.Selling_Package AS `Item Selling Package`,
stockitem.Buying_Package AS `Item Buying Package`,
stockitem.Brand AS `ItemBrand`,
stockitem.Size As `Item Size`,
stockitem.Lead_Time_Days AS `Item Lead Time (Days)`,
stockitem.Quantity_Per_Outer AS `Item Quantity Per Outer`,
stockitem.Is_Chiller_Stock AS `Is Chiller Item Stock`,
stockitem.Barcode AS `Item Barcode`,
stockitem.Tax_Rate AS `Item Tax Rate`,
stockitem.Unit_Price AS `Item Unit Price`,
stockitem.Recommended_Retail_Price AS `Item Recommended Retail Price`,
stockitem.Typical_Weight_Per_Unit AS `Item Typical Weight Per Unit`,
orderDate.ISO_Week_Number AS `Order ISO Week Number`,
orderDate.Date AS `Order Date`,
orderDate.Day_Number AS `Order Day Number`,
orderDate.Day AS `Order Day`,
orderDate.Month AS `Order Month`,
orderDate.Short_Month AS `Order Short Month`,
orderDate.Calendar_Month_Number AS `Order Calendar Month Number`,
orderDate.Calendar_Month_Label AS `Order Calendar Month Label`,
orderDate.Calendar_Year AS `Order Calendar Year`,
orderDate.Calendar_Year_Label AS `Order Calendar Year Label`,
orderDate.Fiscal_Month_Number AS `Order Fiscal Month Number`,
orderDate.Fiscal_Month_Label AS `Order Fiscal Month Label`,
orderDate.Fiscal_Year AS `Order Fiscal Year`,
orderDate.Fiscal_Year_Label AS `Order Fiscal Year Label`,
pickerDate.Date AS `Picker Date`,
pickerDate.Day_Number AS `Picker Day Number`,
pickerDate.Day AS `Picker Day`,
pickerDate.Month AS `Picker Month`,
pickerDate.Short_Month AS `Picker Short Month`,
pickerDate.Calendar_Month_Number AS `Picker Calendar Month Number`,
pickerDate.Calendar_Month_Label AS `Picker Calendar Month Label`,
pickerDate.Calendar_Year AS `Picker Calendar Year`,
pickerDate.Calendar_Year_Label AS `Picker Calendar Year Label`,
pickerDate.Fiscal_Month_Number AS `Picker Fiscal Month Number`,
pickerDate.Fiscal_Month_Label AS `Picker Fiscal Month Label`,
pickerDate.Fiscal_Year AS `Picker Fiscal Year`,
pickerDate.Fiscal_Year_Label AS `Picker Fiscal Year Label`,
pickerDate.ISO_Week_Number AS `Picker ISO Week Number`,
SalesPerson.WWI_Employee_ID AS `Sales Person Code`,
SalesPerson.Employee AS `Sales Person Name`,
SalesPerson.Preferred_Name AS `Sales Person Preferred Name`,
SalesPerson.Is_Salesperson AS `Is Sales Person`,
PickerPerson.WWI_Employee_ID AS `Picker Person Code`,
PickerPerson.Employee AS `Picker Person Name`,
PickerPerson.Preferred_Name AS `Picker Person Preferred Name`,
PickerPerson.Is_Salesperson AS `Is Picker Person`,
orders.WWI_Order_ID AS `Order Code`,
orders.WWI_Backorder_ID AS `Order Backorder Code`,
orders.Description AS `Order Description`,
orders.Package AS `Order Package`,
orders.Quantity AS `Order Quantity`,
orders.Unit_Price AS `Order Unit Price`,
orders.Tax_Rate AS `Order Tax Rate`,
orders.Total_Excluding_Tax AS `Order Total Excluding Tax`,
orders.Tax_Amount AS `Order Tax Amount`,
orders.Total_Including_Tax AS `Order Total Including Tax`
FROM Fact.Order AS orders LEFT OUTER JOIN
Dimension.City AS city ON orders.City_Key = city.City_Key LEFT OUTER JOIN
Dimension.Customer AS customer ON orders.Customer_Key = customer.Customer_Key LEFT OUTER JOIN
Dimension.Stock_Item AS stockitem ON orders.Stock_Item_Key = stockitem.Stock_Item_Key LEFT OUTER JOIN
Dimension.Date AS orderDate ON orders.Order_Date_Key = orderDate.Date LEFT OUTER JOIN
Dimension.Date AS pickerDate ON orders.Picked_Date_Key = pickerDate.Date LEFT OUTER JOIN
Dimension.Employee AS SalesPerson ON orders.Salesperson_Key = SalesPerson.Employee_Key LEFT OUTER JOIN
Dimension.Employee AS PickerPerson ON orders.Salesperson_Key = PickerPerson.Employee_Key AND orders.Picker_Key = PickerPerson.Employee_Key
*/