---
config:
  layout: dagre
  font-size: 15pt
  elk:
    mergeEdges: true
    cycleBreakingStrategy: MODEL_ORDER
    nodePlacementStrategy: NETWORK_SIMPLEX
    look: neo
---
erDiagram
direction LR
classDef movement font-family:tahoma, font-size:15pt, color:darkorchid, stroke:darkorchid, stroke-width:1px, fill:#c7e8e0;
classDef order font-family:tahoma, font-size:15pt, color:#c04b86, stroke:#c04b86, stroke-width:1px, fill:#e9ddc6;
classDef purchase font-family:tahoma, font-size:15pt, color:#2d7373, stroke:#2d7373, stroke-width:1px, fill:#cce3cf;
classDef sale font-family:tahoma, font-size:15pt, color:#4b86c0, stroke:#4b86c0, stroke-width:1px, fill:#dee3cc;
classDef stock_holding font-family:tahoma, font-size:15pt, color:#fbe9ee, stroke:#fbe9ee, stroke-width:1px, fill:#b45757;
classDef transaction font-family:tahoma, font-size:15pt, color:#ffffcc, stroke:#ffffcc, stroke-width:1px, fill:#51484f;
classDef dimension font-family:tahoma, font-size:15pt, color:#392e3b, stroke:#392e3b, stroke-width:1px, fill:#e9a4f5;
classDef integration font-family:tahoma, font-size:15pt, color:#f3eaef, stroke:#f3eaef, stroke-width:1px, fill:#531b3a;
classDef audit font-family:tahoma, font-size:15pt, color:#6936b5, stroke:#6936b5, stroke-width:1px, fill:#f5e5a4;

city_staging ||--|| city: "data loading"
customer_staging ||--|| customer: "data loading"
employee_staging ||--|| employee: "data loading"
paymentmethod_staging ||--|| payment_method: "data loading"
stockitem_staging ||--|| stock_item: "data loading"
supplier_staging ||--|| supplier: "data loading"
transactiontype_staging ||--|| transaction_type: "data loading"
movement_staging ||--|| movement: "data loading"
order_staging ||--|| order: "data loading"
purchase_staging ||--|| purchase: "data loading"
sale_staging ||--|| sale: "data loading"
stockholding_staging ||--|| stock_holding: "data loading"
transaction_staging ||--|| transaction: "data loading"

date ||--|{ movement :"Date Key"
date ||--|{ order :"Order date Key"
date ||--|{ order :"Picked Date Key"
date ||--|{ purchase :"Date Key"
date ||--|{ sale :"Delivery Date Key"
date ||--|{ sale :"Invoice Date Key"
date ||--|{ transaction :"Date Key"

city ||--o{ order :"City Key"
city ||--o{ sale :"City Key"

customer ||--|{ movement :"Customer Key"
customer ||--|{ order :"Customer Key"
customer ||--|{ sale :"Customer Key"
customer ||--|{ sale :"Bill To Customer Key"
customer ||--|{ transaction :"Customer Key"
customer ||--|{ transaction :"Bill To Customer Key"



employee ||--|{ order :"Picker Key"
employee ||--|{ order :"Salesperson Key"
employee ||--|{ sale :"Salesperson Key"

payment_method ||--|{ transaction :"Payment Method Key"

stock_item ||--|{ movement :"Stock Item Key"
stock_item ||--|{ order :"Stock Item Key"
stock_item ||--|{ purchase :"Stock Item Key"
stock_item ||--|{ sale :"Stock Item Key"
stock_item ||--|{ stock_holding :"Stock Item Key"

supplier ||--|{ movement :"Supplier Key"
supplier ||--|{ purchase :"Supplier Key"
supplier ||--|{ transaction :"Supplier Key"

transaction_type ||--|{ movement :"Transaction Type Key"
transaction_type ||--|{ transaction :"Transaction Type Key"


city_staging["Integration.City_Staging"]:::integration {
int city_staging_key    UK    "Row ID within the staging table"
int wwi_city_id "Numeric ID used for reference to a city within the WWI database"
string  city    "Formal name of the city"
string  state_province  "State or province for this city"
string  country "Country name"
string  continent   "Continent that this city is on"
string  sales_territory "Sales territory for this StateProvince"
string  region  "Name of the region"
string  subregion   "Name of the subregion"
geography   location    "Geographic location of the city"
bigint  latest_recorded_population  "Latest available population for the City"
timestamp   valid_from  "Valid from this date and time"
timestamp   valid_to    "Valid until this date and time"
}
customer_staging["Integration.Customer_Staging"]:::integration {
int customer_staging_key    UK    "Row ID within the staging table"
int wwi_customer_id "Numeric ID used for reference to a customer within the WWI database"
string  customer    "Customer's full name (usually a trading name)"
string  bill_to_customer    "Bill to customer's full name"
string  category    "Customer's category"
string  buying_group    "Customer's buying group"
string  primary_contact "Primary contact"
string  postal_code "Delivery postal code for the customer"
timestamp   valid_from  "Valid from this date and time"
timestamp   valid_to    "Valid until this date and time"
}
employee_staging["Integration.Employee_Staging"]:::integration {
int employee_staging_key    UK    "Row ID within the staging table"
int wwi_employee_id "Numeric ID (PersonID) in the WWI database"
string  employee    "Full name for this person"
string  preferred_name  "Name that this person prefers to be called"
bool    is_salesperson  "Is this person a staff salesperson?"
varbinary(MAX)  photo   "Photo of this person"
timestamp   valid_from  "Valid from this date and time"
timestamp   valid_to    "Valid until this date and time"
}
etl_cutoff["Integration.ETL Cutoff"]:::audit {
    string table_name   "Table Name"
    timestamp   cutofftime  "Time up to which data has been loaded"
}
lineage["Integration.Lineage"]:::audit {
    int lineage_key UK "DW key for lineage data"
    timestamp   data_load_started   "Time when the data load attempt began"
    string  table_name  "Name of the table for this data load event"
    timestamp   data_load_completed "Time when the data load attempt completed (successfully or not)"
    bool    was_successful  "Was the attempt successful?"
    timestamp   source_system_cutoff_time   "Time that rows from the source system were loaded up until"
}
movement_staging["Integration.Movement_Staging"]:::integration {
bigint  movement_staging_key    UK    "DW key for a row in the Movement fact"
date    date_key    "Transaction date"
int stock_item_key  "Stock item for this purchase order"
int customer_key    "Customer (if applicable)"
int supplier_key    "Supplier (if applicable)"
int transaction_type_key    "Type of transaction"
int wwi_stock_item_transaction_id   "Stock item transaction ID in source system"
int wwi_invoice_id  "Invoice ID in source system"
int wwi_purchase_order_id   "Purchase order ID in source system"
int quantity    "Quantity of stock movement (positive is incoming stock, negative is outgoing)"
int wwi_stock_item_id   "Stock Item ID in source system"
int wwi_customer_id "Customer ID in source system"
int wwi_supplier_id "Supplier ID in source system"
int wwi_transaction_type_id "Transaction Type ID in source system"
timestamp   last_modifed_when   "When this row was last modified"
}
order_staging["Integration.Order_Staging"]:::integration {
bigint  order_staging_key   UK   "DW key for a row in the Order fact"
int city_key    "City for this order"
int customer_key    "Customer for this order"
int stock_item_key  "Stock item for this order"
date    order_date_key  "Order date for this order"
date    picked_date_key "Picked date for this order"
int salesperson_key "Salesperson for this order"
int picker_key  "Picker for this order"
int wwi_order_id    "OrderID in source system"
int wwi_backorder_id    "BackorderID in source system"
string  description "Description of the item supplied (Usually the stock item name but can be overridden)"
string  package "Type of package to be supplied"
int quantity    "Quantity to be supplied"
number  unit_price  "Unit price to be charged"
number  tax_rate    "Tax rate to be applied"
number  total_excluding_tax "Total amount excluding tax"
number  tax_amount  "Total amount of tax"
number  total_including_tax "Total amount including tax"
int lineage_key "Lineage Key for the data load for this row"
int wwi_city_id "City ID in source system"
int wwi_customer_id "Customer ID in source system"
int wwi_stock_item_id   "Stock Item ID in source system"
int wwi_salesperson_id  "Salesperson person ID in source system"
int wwi_picker_id   "Picker person ID in source system"
timestamp   last_modified_when  "When this row was last modified"
}
paymentmethod_staging["Integration.PaymentMethod_Staging"]:::integration {
int payment_method_staging_key  UK  "Row ID within the staging table"
int wwi_payment_method_id   "Numeric ID for the payment method in the WWI database"
string  payment_method  "Payment method name"
timestamp   valid_from  "Valid from this date and time"
timestamp   valid_to    "Valid until this date and time"
}
purchase_staging["Integration.Purchase_Staging"]:::integration {
    bigint  purchase_staging_key    UK    "DW key for a row in the Purchase fact"
    date    date_key    "Purchase order date"
    int supplier_key    "Supplier for this purchase order"
    int stock_item_key  "Stock item for this purchase order"
    int wwi_purchase_order_id   "Purchase order ID in source system"
    int ordered_outers  "Quantity of outers (ordering packages)"
    int ordered_quantity    "Quantity of inners (selling packages)"
    int received_outers "Received outers (so far)"
    string  package "Package ordered"
    bool    is_order_finalized  "Is this purchase order now finalized?"
    int wwi_supplier_id "Supplier ID in source system"
    int wwi_stock_item_id   "Stock Item ID in source system"
    timestamp   last_modified_when  "When this row was last modified"
}
sale_staging["Integration.Sale_Staging"]:::integration {
    bigint  sale_staging_key    UK    "DW key for a row in the Sale fact"
    int city_key    "City for this invoice"
    int customer_key    "Customer for this invoice"
    int bill_to_customer_key    "Bill To Customer for this invoice"
    int stock_item_key  "Stock item for this invoice"
    date    invoice_date_key    "Invoice date for this invoice"
    date    delivery_date_key   "Date that these items were delivered"
    int salesperson_key "Salesperson for this invoice"
    int wwi_invoice_id  "InvoiceID in source system"
    string  description "Description of the item supplied (Usually the stock item name but can be overridden)"
    string  package "Type of package supplied"
    int quantity    "Quantity supplied"
    number  unit_price  "Unit price charged"
    number  tax_rate    "Tax rate applied"
    number  total_excluding_tax "Total amount excluding tax"
    number  tax_amount  "Total amount of tax"
    number  profit  "Total amount of profit"
    number  total_including_tax "Total amount including tax"
    int total_dry_items "Total number of dry items"
    int total_chiller_items "Total number of chiller items"
    int wwi_city_id "City ID in source system"
    int wwi_customer_id "Customer ID in source system"
    int wwi_bill_to_customer_id "Bill to Customer ID in source system"
    int wwi_stock_item_id   "Stock Item ID in source system"
    int wwi_salesperson_id  "Salesperson person ID in source system"
    timestamp   last_modified_when  "When this row was last modified"
}
stockholding_staging["Integration.StockHolding_Staging"]:::integration {
    bigint  stock_holding_staging_key   UK   "DW key for a row in the Stock Holding fact"
    int stock_item_key  "Stock item being held"
    int quantity_on_hand    "Quantity on hand"
    string  bin_location    "Bin location (where is this stock in the warehouse)"
    int last_stocktake_quantity "Quantity present at last stocktake"
    number  last_cost_price "Unit cost when the stock item was last purchased"
    int reorder_level   "Quantity below which reordering should take place"
    int target_stock_level  "Typical stock level held"
    int wwi_stock_item_id   "Stock Item ID in source system"
}
stockitem_staging["Integration.StockItem_Staging"]:::integration {
    int stock_item_staging_key  UK  "Row ID within the staging table"
    int wwi_stock_item_id   "Numeric ID used for reference to a stock item within the WWI database"
    string  stock_item  "Full name of a stock item (but not a full description)"
    string  color   "Color (optional) for this stock item"
    string  selling_package "Usual package for selling units of this stock item"
    string  buying_package  "Usual package for selling outers of this stock item (ie cartons, boxes, etc.)"
    string  brand   "Brand for the stock item (if the item is branded)"
    string  size    "Size of this item (eg: 100mm)"
    int lead_time_days  "Number of days typically taken from order to receipt of this stock item"
    int quantity_per_outer  "Quantity of the stock item in an outer package"
    bool    is_chiller_stock    "Does this stock item need to be in a chiller?"
    string  barcode "Barcode for this stock item"
    number  tax_rate    "Tax rate to be applied"
    number  unit_price  "Selling price (ex-tax) for one unit of this product"
    number  recommended_retail_price    "Recommended retail price for this stock item"
    number  typical_weight_per_unit "Typical weight for one unit of this product (packaged)"
    varbinary(MAX)  photo   "Photo of the product"
    timestamp   valid_from  "Valid from this date and time"
    timestamp   valid_to    "Valid until this date and time"
}
supplier_staging["Integration.Supplier_Staging"]:::integration {
    int supplier_staging_key    UK    "Row ID within the staging table"
    int wwi_supplier_id "Numeric ID used for reference to a supplier within the WWI database"
    string  supplier    "Supplier's full name (usually a trading name)"
    string  category    "Supplier's category"
    string  primary_contact "Primary contact"
    string  supplier_reference  "Supplier reference for our organization (might be our account number at the supplier)"
    int payment_days    "Number of days for payment of an invoice (ie payment terms)"
    string  postal_code "Delivery postal code for the supplier"
    timestamp   valid_from  "Valid from this date and time"
    timestamp   valid_to    "Valid until this date and time"
}
transaction_staging["Integration.Transaction_Staging"]:::integration {
    bigint  transaction_staging_key UK "DW key for a row in the Transaction fact"
    date    date_key    "Transaction date"
    int customer_key    "Customer (if applicable)"
    int bill_to_customer_key    "Bill to customer (if applicable)"
    int supplier_key    "Supplier (if applicable)"
    int transaction_type_key    "Type of transaction"
    int payment_method_key  "Payment method (if applicable)"
    int wwi_customer_transaction_id "Customer transaction ID in source system"
    int wwi_supplier_transaction_id "Supplier transaction ID in source system"
    int wwi_invoice_id  "Invoice ID in source system"
    int wwi_purchase_order_id   "Purchase order ID in source system"
    string  supplier_invoice_number "Supplier invoice number (if applicable)"
    number  total_excluding_tax "Total amount excluding tax"
    number  tax_amount  "Total amount of tax"
    number  total_including_tax "Total amount including tax"
    number  outstanding_balance "Amount still outstanding for this transaction"
    bool    is_finalized    "Has this transaction been finalized?"
    int wwi_customer_id "Customer ID in source system"
    int wwi_bill_to_customer_id "Bill to Customer ID in source system"
    int wwi_supplier_id "Supplier ID in source system"
    int wwi_transaction_type_id "Transaction Type ID in source system"
    int wwi_payment_method_id   "Payment method ID in source system"
    timestamp   last_modified_when  "When this row was last modified"
}
transactiontype_staging["Integration.TransactionType_Staging"]:::integration {
    int transaction_type_staging_key    UK    "Row ID within the staging table"
    int wwi_transaction_type_id "Numeric ID used for reference to a transaction type within the WWI database"
    string  transaction_type    "Full name of the transaction type"
    timestamp   valid_from  "Valid from this date and time"
    timestamp   valid_to    "Valid until this date and time"
}

city["Dimension.City"]:::dimension {
    int city_key    PK        "DW key for the city dimension"
    int wwi_city_id     "Numeric ID used for reference to a city within the WWI database"
    string  city        "Formal name of the city"
    string  state_province      "State or province for this city"
    string  country     "Country name"
    string  continent       "Continent that this city is on"
    string  sales_territory     "Sales territory for this StateProvince"
    string  region      "Name of the region"
    string  subregion       "Name of the subregion"
    string  location        "Geographic location of the city"
    int latest_recorded_population      "Latest available population for the City"
    timestamp   valid_from      "Valid from this date and time"
    timestamp   valid_to        "Valid until this date and time"
    int lineage_key     "Lineage Key for the data load for this row"
}
customer["Dimension.Customer"]:::dimension{
    int customer_key    PK  "DW key for the customer dimension"
    int wwi_customer_id     "Numeric ID used for reference to a customer within the WWI database"
    string  customer        "Customer's full name (usually a trading name)"
    string  bill_to_customer        "Bill to customer's full name"
    string  category        "Customer's category"
    string  buying_group        "Customer's buying group"
    string  primary_contact     "Primary contact"
    string  postal_code     "Delivery postal code for the customer"
    timestamp   valid_from      "Valid from this date and time"
    timestamp   valid_to        "Valid until this date and time"
    int lineage_key     "Lineage Key for the data load for this row"
}
date["Dimension.Date"]:::dimension{
    date    date    PK  "DW key for date dimension (actual date is used for key)"
    int day_number      "Day of the month"
    string  day     "Day name"
    string  month       "Month name (ie September)"
    string  short_month     "Short month name (ie Sep)"
    int calendar_month_number       "Calendar month number"
    string  calendar_month_label        "Calendar month label (ie CY2015Jun)"
    int calendar_year       "Calendar year (ie 2015)"
    string  calendar_year_label     "Calendar year label (ie CY2015)"
    int fiscal_month_number     "Fiscal month number"
    string  fiscal_month_label      "Fiscal month label (ie FY2015Feb)"
    int fiscal_year     "Fiscal year (ie 2016)"
    string  fiscal_year_label       "Fiscal year label (ie FY2015)"
    int iso_week_number     "ISO week number (ie 25)"
}
employee["Dimension.Employee"]:::dimension{
    int employee_key    PK  "DW key for the employee dimension"
    int wwi_employee_id     "Numeric ID (PersonID) in the WWI database"
    string  employee        "Full name for this person"
    string  preferred_name      "Name that this person prefers to be called"
    bool    is_salesperson      "Is this person a staff salesperson?"
    varbinary(MAX)  photo       "Photo of this person"
    timestamp   valid_from      "Valid from this date and time"
    timestamp   valid_to        "Valid until this date and time"
    int lineage_key     "Lineage Key for the data load for this row"
}
payment_method["Dimension.Payment Method"]:::dimension{
    int payment_method_key  PK  "DW key for the payment method dimension"
    int wwi_payment_method_id   "Numeric ID for the payment method in the WWI database"
    string  payment_method  "Payment method name"
    timestamp   valid_from  "Valid from this date and time"
    timestamp   valid_to    "Valid until this date and time"
    int lineage_key "Lineage Key for the data load for this row"
}
stock_item["Dimension.Stock Item"]:::dimension {
    int stock_item_key  PK  "DW key for the stock item dimension"
    int wwi_stock_item_id   "Numeric ID used for reference to a stock item within the WWI database"
    string  stock_item  "Full name of a stock item (but not a full description)"
    string  color   "Color (optional) for this stock item"
    string  selling_package "Usual package for selling units of this stock item"
    string  buying_package  "Usual package for selling outers of this stock item (ie cartons, boxes, etc.)"
    string  brand   "Brand for the stock item (if the item is branded)"
    string  size    "Size of this item (eg: 100mm)"
    int lead_time_days  "Number of days typically taken from order to receipt of this stock item"
    int quantity_per_outer  "Quantity of the stock item in an outer package"
    bool    is_chiller_stock    "Does this stock item need to be in a chiller?"
    string  barcode "Barcode for this stock item"
    number    tax_rate    "Tax rate to be applied"
    number    unit_price  "Selling price (ex-tax) for one unit of this product"
    number    recommended_retail_price    "Recommended retail price for this stock item"
    number    typical_weight_per_unit "Typical weight for one unit of this product (packaged)"
    varbinary(MAX)  photo   "Photo of the product"
    timestamp   valid_from  "Valid from this date and time"
    timestamp   valid_to    "Valid until this date and time"
    int lineage_key "Lineage Key for the data load for this row"
}
supplier["Dimension.Supplier"]:::dimension{
    int supplier_key    PK    "DW key for the supplier dimension"
    int wwi_supplier_id "Numeric ID used for reference to a supplier within the WWI database"
    string  supplier    "Supplier's full name (usually a trading name)"
    string  category    "Supplier's category"
    string  primary_contact "Primary contact"
    string  supplier_reference  "Supplier reference for our organization (might be our account number at the supplier)"
    int payment_days    "Number of days for payment of an invoice (ie payment terms)"
    string  postal_code "Delivery postal code for the supplier"
    timestamp   valid_from  "Valid from this date and time"
    timestamp   valid_to    "Valid until this date and time"
    int lineage_key "Lineage Key for the data load for this row"
}
transaction_type["Dimension.Transaction Type"]:::dimension{
    int transaction_type_key    PK    "DW key for the transaction type dimension"
    int wwi_transaction_type_id "Numeric ID used for reference to a transaction type within the WWI database"
    string  transaction_type    "Full name of the transaction type"
    timestamp   valid_from  "Valid from this date and time"
    timestamp   valid_to    "Valid until this date and time"
    int lineage_key "Lineage Key for the data load for this row"
}

movement["Fact.Movement"]:::movement{
    int movement_key    UK    "DW key for a row in the Movement fact"
    date    date_key    FK    "Transaction date"
    int stock_item_key  FK  "Stock item for this purchase order"
    int customer_key    FK    "Customer (if applicable)"
    int supplier_key    FK    "Supplier (if applicable)"
    int transaction_type_key    "Type of transaction"
    int wwi_stock_item_transaction_id   "Stock item transaction ID in source system"
    int wwi_invoice_id  "Invoice ID in source system"
    int wwi_purchase_order_id   "Purchase order ID in source system"
    int quantity    "Quantity of stock movement (positive is incoming stock, negative is outgoing)"
    int lineage_key "Lineage Key for the data load for this row"
}
order["Fact.Order"]:::order {
    int  order_key  UK   "DW key for a row in the Order fact"
    int city_key    FK    "City for this order"
    int customer_key    FK    "Customer for this order"
    int stock_item_key  FK  "Stock item for this order"
    date    order_date_key  FK  "Order date for this order"
    date    picked_date_key FK "Picked date for this order"
    int salesperson_key FK "Salesperson for this order"
    int picker_key  FK  "Picker for this order"
    int wwi_order_id    "OrderID in source system"
    int wwi_backorder_id    "BackorderID in source system"
    string  description "Description of the item supplied (Usually the stock item name but can be overridden)"
    string  package "Type of package to be supplied"
    int quantity    "Quantity to be supplied"
    number  unit_price  "Unit price to be charged"
    number  tax_rate    "Tax rate to be applied"
    number  total_excluding_tax "Total amount excluding tax"
    number  tax_amount  "Total amount of tax"
    number  total_including_tax "Total amount including tax"
    int lineage_key "Lineage Key for the data load for this row"
}
purchase["Fact.Purchase"]:::purchase{
    int purchase_key    UK    "DW key for a row in the Purchase fact"
    date    date_key    FK    "Purchase order date"
    int supplier_key    FK    "Supplier for this purchase order"
    int stock_item_key    FK  "Stock item for this purchase order"
    int wwi_purchase_order_id   "Purchase order ID in source system"
    int ordered_outers  "Quantity of outers (ordering packages)"
    int ordered_quantity    "Quantity of inners (selling packages)"
    int received_outers "Received outers (so far)"
    string  package "Package ordered"
    bit is_order_finalized  "Is this purchase order now finalized?"
    int lineage_key "Lineage Key for the data load for this row"
}
sale["Fact.Sale"]:::sale {
    int sale_key    UK  "DW key for a row in the Sale fact"
    int city_key    FK  "City for this invoice"
    int customer_key    FK  "Customer for this invoice"
    int bill_to_customer_key    FK  "Bill To Customer for this invoice"
    int stock_item_key    FK  "Stock item for this invoice"
    date    invoice_date_key    FK  "Invoice date for this invoice"
    date    delivery_date_key    FK "Date that these items were delivered"
    int salesperson_key    FK "Salesperson for this invoice"
    int wwi_invoice_id  "InvoiceID in source system"
    string  description "Description of the item supplied (Usually the stock item name but can be overridden)"
    string  package "Type of package supplied"
    int quantity  "Quantity supplied"
    number  unit_price  "Unit price charged"
    number  tax_rate  "Tax rate applied"
    number  total_excluding_tax "Total amount excluding tax"
    number  tax_amount  "Total amount of tax"
    number  profit  "Total amount of profit"
    number  total_including_tax "Total amount including tax"
    int total_dry_items "Total number of dry items"
    int total_chiller_items "Total number of chiller items"
    int lineage_key "Lineage Key for the data load for this row"
}
transaction["Fact.Transaction"]:::transaction{
    int transaction_key UK "DW key for a row in the Transaction fact"
    date    date_key    FK    "Transaction date"
    int customer_key    FK    "Customer (if applicable)"
    int bill_to_customer_key    FK    "Bill to customer (if applicable)"
    int supplier_key    FK    "Supplier (if applicable)"
    int transaction_type_key    FK    "Type of transaction"
    int payment_method_key    FK  "Payment method (if applicable)"
    int wwi_customer_transaction_id "Customer transaction ID in source system"
    int wwi_supplier_transaction_id "Supplier transaction ID in source system"
    int wwi_invoice_id  "Invoice ID in source system"
    int wwi_purchase_order_id   "Purchase order ID in source system"
    string  supplier_invoice_number "Supplier invoice number (if applicable)"
    number  total_excluding_tax "Total amount excluding tax"
    number  tax_amount  "Total amount of tax"
    number  total_including_tax "Total amount including tax"
    number  outstanding_balance "Amount still outstanding for this transaction"
    bool    is_finalized    "Has this transaction been finalized?"
    int lineage_key "Lineage Key for the data load for this row"
}
stock_holding["Fact.Stock Holding"]:::stock_holding {
    int stock_holding_key   UK   "DW key for a row in the Stock Holding fact"
    int stock_item_key  FK  "Stock item being held"
    int quantity_on_hand    "Quantity on hand"
    string  bin_location    "Bin location (where is this stock in the warehouse)"
    int last_stocktake_quantity "Quantity present at last stocktake"
    number  last_cost_price "Unit cost when the stock item was last purchased"
    int reorder_level   "Quantity below which reordering should take place"
    int target_stock_level  "Typical stock level held"
    int lineage_key "Lineage Key for the data load for this row"
}
